### PR TITLE
Update default shorteners list

### PR DESCRIPTION
**Pull request by ascastro**
There were 2 shortener domains without extension.
Removed the following domains:
- to
- tk

This was causing domains like 'www.whale.to' to be matched with the domain regex.

### CODE REVIEW

**Comment by jbilbo** [comment]
This justifies a bugfix release.

**Comment by mudge** [comment]
`.tk` is genuinely [a shortener](http://www.dot.tk/en/index.html?lang=en) where you can register a top-level domain to redirect to another URL.

I'm not sure about `.to` though which came from the (currently unavailable) [LongURL list](http://longurl.org/services).

**Comment by ascastro** [comment]
Is the `to` the same as https://anon.to/ ?
If it is, then we should add `anon.to`, rather than `to`.

I didn't know about the `.tk` one - sorry about that.

**Comment by ascastro** [comment]
I've also find this: http://bit.do/list-of-url-shorteners.php

And it looks like there's a `u.to` too.

**Comment by mudge** [comment]
Let's remove the bare `.to` and maybe update the list with any missing from http://bit.do/list-of-url-shorteners.php and http://www.hongkiat.com/blog/url-shortening-services-the-ultimate-list/?

**Comment by ascastro** [comment]
sure - on it!

**Comment by ascastro** [comment]
The list is now updated.
I've also changed the commit message, to reflect the change.

**Comment by jbilbo** [comment]
@ascastro sorry, could you insert them in alphabetic order?

**Comment by ascastro** [comment]
@jbilbo done.

**Pull request merged**
